name: CI/CD

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Determine Modal Environment Name
        id: set_env_name
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=env_name::dev"
          else
            echo "::set-output name=env_name::pr${{ github.event.pull_request.number }}"
          fi

      - name: Create and Set Modal Environment
        run: |
          ENV_NAME=${{ steps.set_env_name.outputs.env_name }}
          echo "Attempting to create or set environment: $ENV_NAME"
          
          echo "Running 'modal environment create' command..."
          CREATE_OUTPUT=$(modal environment create $ENV_NAME 2>&1)
          CREATE_EXIT_CODE=$?
          echo "Command run complete."

          echo "Create command output: $CREATE_OUTPUT"
          echo "Create command exit code: $CREATE_EXIT_CODE"

          if [ $CREATE_EXIT_CODE -ne 0 ]; then
            echo "An error occurred, but continuing for debugging."
          else
            echo "Environment '$ENV_NAME' created successfully."
          fi

          echo "Setting environment..."
          modal config set-environment $ENV_NAME
          echo "Environment '$ENV_NAME' is now set as the current environment."

      - name: Deploy job
        run: |
          modal deploy my_package.my_file
